#!/bin/sh

# exit script on error
set -e

# assign usage
usage=$(
	cat <<EOUSAGE
Ini Curd v0.0.1

Usage: $0 [-hiv] <ini_file> <section> <key> <value>

Update value of key in [section] find in ini file

	-h	Print usage and exit.
	-i	Modify ini file inplace.
	-v	Print message on successfully update.
		(Only work if modify inplace.)
EOUSAGE
)

# parse command-line arguments
inplace=false
verbose=false
while getopts ":hiv" opt; do
	case ${opt} in
	h)
		echo "$usage"
		exit 0
		;;
	v) verbose=true ;;
	i) inplace=true ;;
	\?)
		echo "$usage" >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

# check argument count
if [ $# -lt 1 ]; then
	echo "Error: <ini_file> is needed!" >&2
	echo "$usage" >&2
	exit 1
fi

# check file exist
ini_file="$1"
if [ ! -f "$ini_file" ]; then
	echo "Error: $ini_file not found" >&2
	exit 1
fi

# check argument count
if [ $# -lt 3 ]; then
	echo "Error: <section> <key> is needed!" >&2
	echo "$usage" >&2
	exit 1
fi
section="$2"
key="$3"

# check section exists in ini
grep_expr_check_section='^\['$section']'
if ! grep -q "$grep_expr_check_section" "$ini_file"; then
	echo "Error: [$section] not found in $ini_file" >&2
	exit 1
fi

# check key exists in section of ini

# script explain:
#     1. sed delete all lines from ini_file except line with matched key
#     2. grep check pattern ^[[:space:]]*$key[[:space:]]*= exist from pipe

sed_script_get_section_only_content='/^\['$section'\]$/,/^\[/!d;'
grep_expr_check_key='^[[:space:]]*'$key'[[:space:]]*='

if ! sed "$sed_script_get_section_only_content" "$ini_file" | grep -q $grep_expr_check_key; then
	echo "Error: $key not found in section [$section] of $ini_file" >&2
	exit 1
fi

if [ $# -lt 4 ]; then
	echo "Error: <value> is needed!" >&2
	echo "$usage" >&2
	exit 1
fi
shift 3
value=$(echo "$@" | sed 's/\//\\\//g' | sed 's/\\/\\\\/g')

# update value

# sed explain:
#   1. get section only content (same as last sed movement)
#   2. (s///g) replace ^[[:space:]]*$key[[:space:]]*=[[:space:]]* into $key = $value  (delete key part)
sed_script_update_value='/^\['$section'\]$/,/^\[/ s/^[[:space:]]*'$key'[[:space:]]*=[[:space:]]*[^#;]*/'$key' = '$value' /g;'

if $inplace; then
	if sed -i "$sed_script_update_value" "$ini_file" && $verbose; then
		echo "Success: update [$section]:$key = $value"
	fi
else
	sed "$sed_script_update_value" "$ini_file"
fi
